### ISSUE TITLE
PRs for the team UI Tests are not managed by maintainers

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/kanbanbot#20]
PR labelled "TE" + "E2E tests" are reviewed only by @PrestaShop/ui-tests-maintainers.

They must not be added to "PR Dashboard" project.

**Comment by Progi1984** [comment]
It's not a duplicate.PR labelled "TE" + "E2E tests" must be excluded from the  "PR Dashboard" project.

**Comment by MatShir** [comment]
add the exception on the issue

**Comment by Progi1984** [comment]
@MatShir Done
